name: Waka Readme

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
    - main
    paths:
    - '.github/workflows/generate_readme_waka.yml'
  
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/generate_readme_waka.yml'

  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - run: echo "CURRENT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV 
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: True
          COMMIT_MESSAGE: "${{ env.CURRENT_DATE }} : Update WakaTime."
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: True
          SYMBOL_VERSION: 3
          SHOW_TOTAL_CODE_TIME: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE: False

          
