name: Waka Readme

on:
  schedule:
    - cron: "0 */24 * * *"
  push:
    branches:
    - main
    paths:
    - '.github/workflows/generate_readme_waka.yml'
  
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/generate_readme_waka.yml'

  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
